{% set name = "python-build" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: 538aab1b64f9828977f84bc63ae570b060a8ed1be419e7870b8b4fc5e6ea553b

build:
  number: 0
  noarch: python
  entry_points:
    - python-build = build.__main__:entrypoint
    - pyproject-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3.4
  run:
    - python >=3.7
    - colorama
    - importlib-metadata >=4.6
    - packaging >=19.0
    - pyproject_hooks
    - tomli >=1.1.0
  run_constrained:
    - build <0

test:
  imports:
    - build
  commands:
    - pip check
    - python-build --help
    - pyproject-build --help
  requires:
    - pip

about:
  home: https://github.com/pypa/build
  license: MIT
  license_file: LICENSE
  summary: A simple, correct PEP 517 build frontend
  doc_url: https://pypa-build.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - henryiii
