{% set name = "python-build" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: 119b2fb462adef986483438377a13b2f42064a2a3a4161f24a0cca698a07ac8c

build:
  number: 0
  noarch: python
  entry_points:
    - python-build = build.__main__:entrypoint
    - pyproject-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - flit-core >=3.8
  run:
    - python >=3.8
    - colorama
    - importlib-metadata >=4.6
    - packaging >=19.0
    - pyproject_hooks
    - tomli >=1.1.0
  run_constrained:
    - build <0

test:
  imports:
    - build
  commands:
    - pip check
    - python-build --help
    - pyproject-build --help
  requires:
    - pip

about:
  home: https://github.com/pypa/build
  license: MIT
  license_file: LICENSE
  summary: A simple, correct PEP 517 build frontend
  doc_url: https://pypa-build.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - henryiii
