{% set name = "python-build" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: 698edd0ea270bde950f53aed21f3a0135672206f3911e0176261a31e0e07b397

build:
  number: 0
  noarch: python
  entry_points:
    - python-build = build.__main__:entrypoint
    - pyproject-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.8
  run:
    - python >={{ python_min }}
    - colorama
    - importlib-metadata >=4.6
    - packaging >=19.0
    - pyproject_hooks
    - tomli >=1.1.0
  run_constrained:
    - build <0

test:
  imports:
    - build
  commands:
    - pip check
    - python-build --help
    - pyproject-build --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pypa/build
  license: MIT
  license_file: LICENSE
  summary: A simple, correct PEP 517 build frontend
  doc_url: https://pypa-build.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - henryiii
