schema_version: 1

context:
  name: python-build
  version: "1.5.1"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/build/build-${{ version }}.tar.gz
  sha256: 94e17f1db803ab22f46049376c44c8437c52090f0dfdf1adc43df56542d644fb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - python-build = build.__main__:entrypoint
      - pyproject-build = build.__main__:entrypoint

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core >=3.11
  run:
    - python >=${{ python_min }}
    - colorama
    - importlib-metadata >=4.6
    - packaging >=24.0
    - pyproject_hooks
    - tomli >=1.1.0
  run_constraints:
    - build <0

tests:
  - python:
      imports:
        - build
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - python-build --help
      - pyproject-build --help

about:
  license: MIT
  license_file: LICENSE
  summary: A simple, correct PEP 517 build frontend
  homepage: https://github.com/pypa/build
  documentation: https://pypa-build.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - henryiii
